const attack;
const defend;
const attackcharacter;
const attackerHP;
const attackerAP;
const attackerCAP;
const defendcharacter;
const defenderHP;
const defenderAP;
const defenderCAP;
const name;
const YourCharacter;
const YourDefender;
const myChar = "";
const myDef = "";